language: python
python:
    - "3.6"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/HAPI-Basic PLATFORMIO_CI_EXTRA_ARGS="--board=iotaap_magnolia"

install:
    - pip install -U platformio
    - platformio update
    - platformio platform install espressif32
    - pio lib -g install $TRAVIS_BUILD_DIR

script:
    - platformio ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS